<a target="_blank" href="https://colab.research.google.com/github/aquinteroz/Proyecto3/blob/main/Notebooks/01%20-%20Numpy/03-NumPy-Exercises.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a
>

# Ejercicios sobre NumPy

Ahora que hemos aprendido sobre NumPy, pongamos a prueba tus conocimientos. Comenzaremos con algunas tareas simples y luego habrá algunas preguntas más complicadas.

#### 1. Importe NumPy como np

#### 2. Cree un arreglo de 10 ceros 

#### 3. Cree un arreglo de 10 unos

#### 4. Cree un arreglo de 10 cincos

#### 5. Cree un arreglo con los enteros del 10 al 50 (ambos inclusive)

#### 6. Cree un arreglo con los enteros impares entre 10 y el 50

#### 7. Cree una matriz $3\times 3$ con valores entre el 0 y el 8

#### 8. Create una matriz identidad $3\times 3$

#### 9. Genere un número aleatorio entre 0 y 1 usando NumPy

#### 10. Utilice NumPy para generar una matriz de 25 números aleatorios muestreados a partir de una distribución normal estándar

#### 11. Cree la siguiente matriz

~~~
array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])
~~~

#### 12. Cree un arreglo con 20 valores linealmente espaciados entre 0 y 1:

## Indexación y selección

Ahora se le proporcionará una matriz inicial (¡asegúrese de ejecutar la celda a continuación!) y se le pedirá que replique los resultados de la matriz resultant::

In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat

#### 13. Escriba código que reproduzca el resultado que se muestra a continuación.

~~~
array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])
~~~

#### 14. Escriba código que reproduzca el resultado que se muestra a continuación.

~~~
20
~~~

#### 15. Escriba código que reproduzca el resultado que se muestra a continuación.

~~~
array([[ 2],
       [ 7],
       [12]])
~~~

#### 16. Escriba código que reproduzca el resultado que se muestra a continuación.
~~~
array([21, 22, 23, 24, 25])
~~~

#### 17. Escriba código que reproduzca el resultado que se muestra a continuación.

~~~
array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])
~~~

## Operaciones con NumPy

#### 18. Calcule la suma de todos los elementos de <tt>mat</tt>

#### 19. Calcule la desviación estándar de los valores de <tt>mat</tt>

#### 20. Calcule la suma por columnas de <tt>mat</tt>

#### 21. Calcule la suma por filas de <tt>mat</tt>